[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tokio-tungstenite = "0.28"
serde_json = "1.0"
server = { path = "../server" }
rand = "0.9.2"
